name: Sync GitHub

on:
  push:
    branches:
      - main  # Cambia "main" por la rama principal de tu repositorio

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync with upstream repository
      run: git pull https://github.com/jonh3rdz/Task.git  # Reemplaza con la URL del repositorio remoto al que deseas sincronizar

    - name: Push changes
      run: git push origin main  # Cambia "main" por la rama principal de tu repositorio
